{
 "title": "CMTS - Cable",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CMTS",
    "query": "show tag values from cmts with key=hostname"
   },
   {
    "name": "FiberNode",
    "query": "Show tag values from cmts with key=ifAlias where hostname=~ /^$CMTS$/ and ifType='129'"
   },
   {
    "name": "ifindex",
    "query": "Show tag values from cmts_fn with key=ifIndex where fnDescr=~ /^$FiberNode$/ and hostname=~ /^$CMTS$/"
   }
  ]
 },
 "panels": [
  {
   "title": "CM Num",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Modems" }
   ],
   "targets": [
    {
     "alias": "$FiberNode - Online Total CM",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmts",
     "select": [
      [
       { "params": [ "registeredCMCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$CMTS$/" },
      { "condition": "AND", "key": "ifIndex", "operator": "=~", "value": "/^$ifindex$/" }
     ]
    },
    {
     "alias": "$FiberNode - $tag_ifDescr - $tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "docsIfUpChannelFrequency" ], "type": "tag" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmts",
     "select": [
      [
       { "params": [ "registeredCMCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$CMTS$/" },
      { "condition": "AND", "key": "ifIndex", "operator": "=~", "value": "/^$ifindex$/" }
     ]
    },
    {
     "alias": "$FiberNode - Offline Total CM",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "docsIfUpChannelFrequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmCount",
     "query": "SELECT sum(\"totalCMCount\") - sum(\"registeredCMCount\") FROM \"cmts\" WHERE (\"ifIndex\" =~ /^$ifindex$/ AND \"hostname\" =~ /^$CMTS$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "registeredCMCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ifAlias", "operator": "=~", "value": "/^$FiberNode$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$CMTS$/" }
     ]
    }
   ]
  },
  {
   "title": "SNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_ifAlias - $tag_ifName - $tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "ifAlias" ], "type": "tag" },
      { "params": [ "docsIfUpChannelFrequency" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmts",
     "query": "SELECT mean(\"docsIfSigQSignalNoise\")  / 10 FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/ AND \"ifAlias\" =~ /^$FiberNode$/) AND $timeFilter GROUP BY time(5m), \"ifAlias\", \"docsIfUpChannelFrequency\", \"ifName\" fill(null)",
     "select": [
      [
       { "params": [ "docsIfSigQSignalNoise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "PG-CASA" },
      { "condition": "AND", "key": "ifAlias", "operator": "=~", "value": "/^$FiberNode$/" }
     ]
    }
   ]
  },
  {
   "title": "FEC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ifAlias - $tag_ifName - $tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100*(non_negative_derivative(mean(\"docsIfSigQCorrecteds\"), 1s)/(non_negative_derivative(mean(\"docsIfSigQUncorrectables\"), 1s) + non_negative_derivative(mean(\"docsIfSigQCorrecteds\"), 1s) + non_negative_derivative(mean(\"docsIfSigQUnerroreds\"), 1s))) AS \"FEC\" FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/ AND \"ifAlias\" =~ /^$FiberNode$/) AND $timeFilter GROUP BY time(5m), \"docsIfUpChannelFrequency\",\"ifName\",\"ifAlias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ifAlias - $tag_ifName - $tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100*(non_negative_derivative(mean(\"docsIfSigQUncorrectables\"), 1s)/(non_negative_derivative(mean(\"docsIfSigQUncorrectables\"), 1s) + non_negative_derivative(mean(\"docsIfSigQCorrecteds\"), 1s) + non_negative_derivative(mean(\"docsIfSigQUnerroreds\"), 1s))) AS \"FEC\" FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/ AND \"ifAlias\" =~ /^$FiberNode$/) AND $timeFilter GROUP BY time(5m), \"docsIfUpChannelFrequency\",\"ifName\",\"ifAlias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "US - Channel Util",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Total Util",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (8*non_negative_derivative(sum(\"ifHCInOctets\"), 1s))/sum(\"ifSpeed\")*100 FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/  and \"ifAlias\" =~ /^$FiberNode$/ and \"ifType\"='205') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$FiberNode - $tag_ifName - $tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmts",
     "query": "SELECT (8*non_negative_derivative(mean(\"ifHCInOctets\"), 1s))/mean(\"ifSpeed\")*100 FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/  and \"ifAlias\" =~ /^$FiberNode$/ and \"ifType\"='205') AND $timeFilter GROUP BY time(5m), \"ifName\", \"ifAlias\",\"docsIfUpChannelFrequency\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ifType", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "DS - Channel Util",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Total Util",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (8*non_negative_derivative(sum(\"ifHCOutOctets\"), 1s)/sum(ifSpeed))*100  FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/  and \"ifAlias\" =~ /\\|$FiberNode\\|/ and \"ifType\"='128') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$FiberNode - $tag_ifName - $tag_docsIfDownChannelFrequency - $tag_ifAlias",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmts",
     "query": "SELECT (8*non_negative_derivative(mean(\"ifHCOutOctets\"), 1s))/mean(\"ifSpeed\")*100 FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/  and \"ifAlias\" =~ /\\|$FiberNode\\|/ and \"ifType\"='128') AND $timeFilter GROUP BY time(5m), \"ifName\", \"ifAlias\",\"docsIfDownChannelFrequency\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ifType", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$FiberNode - Total Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 8*non_negative_derivative(sum(\"ifHCInOctets\"), 1s)  FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/  and \"ifAlias\" =~ /^$FiberNode$/ and \"ifType\"='205') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$FiberNode - $tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmts",
     "query": "SELECT 8*non_negative_derivative(mean(\"ifHCInOctets\"), 1s) FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/  and \"ifAlias\" =~ /^$FiberNode$/ and \"ifType\"='205') AND $timeFilter GROUP BY time(5m), \"ifName\", \"ifAlias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ifType", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$FiberNode - Total Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 8*non_negative_derivative(sum(\"ifHCOutOctets\"), 1s)  FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/  and \"ifAlias\" =~ /\\|$FiberNode\\|/ and \"ifType\"='128') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$FiberNode - $tag_ifName - $tag_ifAlias",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmts",
     "query": "SELECT 8*non_negative_derivative(mean(\"ifHCOutOctets\"), 1s) FROM \"cmts\" WHERE (\"hostname\" =~ /^$CMTS$/ and  \"ifAlias\" =~ /\\|$FiberNode\\|/  and \"ifType\"='128') AND $timeFilter GROUP BY time(5m), \"ifName\", \"ifAlias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ifType", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  }
 ]
}